### ISSUE TITLE
数据集链接失效

### ISSUE THREAD

**Issue by lxq414302** [zao-chao6/PCB_defect_detection_faster_r_cnn#1]
您好，百度网盘数据集链接失效了，能发我一份吗,谢谢！
邮箱1732942781@qq.com

**Comment by zao-chao6** [comment]
非常抱歉，笔者使用的是私有数据集，不能向外公布，网上有现有的coco和voc数据集你可以下载，用于本模型的训练和测试

**Comment by zao-chao6** [comment]
非常抱歉，笔者使用的是私有数据集，不能向外公布，网上有现有的coco和voc数据集你可以下载，用于本模型的训练和测试

**Comment by lxq414302** [comment]
好的，谢谢，关键是真的搜不到

**Comment by lxq414302** [comment]
您好，找的其他的数据集代码跑不了，我就用于毕业设计，不会用于任何商用。

**Comment by lxq414302** [comment]
能加个联系方式不，有关代码想请教下您！
